domain_path: /home/min/fpga/soc/platform_hc05_test_pullup/export/platform_hc05_test_pullup/sw/standalone_microblaze_riscv_0
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
